// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trogsoft.Ectobi.Data;

#nullable disable

namespace Trogsoft.Ectobi.Data.Migrations
{
    [DbContext(typeof(EctoDb))]
    [Migration("20230318125103_TextId")]
    partial class TextId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trogsoft.Ectobi.Data.Schema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schemas");
                });

            modelBuilder.Entity("Trogsoft.Ectobi.Data.SchemaField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SchemaId")
                        .HasColumnType("bigint");

                    b.Property<string>("TextId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long?>("ValuesFromSchemaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchemaId");

                    b.HasIndex("ValuesFromSchemaId");

                    b.ToTable("SchemaFields");
                });

            modelBuilder.Entity("Trogsoft.Ectobi.Data.SchemaField", b =>
                {
                    b.HasOne("Trogsoft.Ectobi.Data.Schema", "Schema")
                        .WithMany("SchemaFields")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trogsoft.Ectobi.Data.Schema", "ValuesFromSchema")
                        .WithMany()
                        .HasForeignKey("ValuesFromSchemaId");

                    b.Navigation("Schema");

                    b.Navigation("ValuesFromSchema");
                });

            modelBuilder.Entity("Trogsoft.Ectobi.Data.Schema", b =>
                {
                    b.Navigation("SchemaFields");
                });
#pragma warning restore 612, 618
        }
    }
}
